sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t rishabhsakhare/docker-react:latest .

script:
  - docker run -e CI=true rishabhsakhare/docker-react npm run test